### PR TITLE
Toasted message now displays properly

### LINKED ISSUE #19: $toasted not showing when changing value
After some debugging, I think the problem lies in the following code:

https://github.com/kirschbaum-development/nova-inline-select/blob/25ac3533ea73392b5befaccbfeb0c484b32d2761/resources/js/components/mixins/inline.js#L25

This piece of code is trying to set the label based on the `field.value`. The problem is that this is the old `value` and not the new one. 

Fixing this would tackle 2 issues:

- First, if the old value is null, $toasted will never show up because is trying to get `label` on null.
- Second, if there was an old value, then the $toasted will show but referencing the old value and not the updated one.

This issues is related with #11 

Can anyone confirm if the issue still persists?

### PR DESCRIPTION
**Pull request by skoyah**
Changed the comparison value being used when trying to obtain the label to be displayed on the `$toasted` message. 

Also minified the js bundle.

This PR fixes #19 .

### CODE REVIEW

**Comment by brandonferens** [comment]
Thanks @skoyah. I will review this hopefully sometime today.

**Comment by skoyah** [comment]
> Thanks @skoyah. I will review this hopefully sometime today.

Thanks! Is really important for our client! 😄

**Comment by skoyah** [comment]
Hey @brandonferens! Any news on this issue?

**Comment by cotton9** [comment]
I'm anxiously awaiting this fix as well.

**Comment by skoyah** [comment]
I hope he has time to fix it soon! :)

**Review by brandonferens — APPROVED** [review]

**Comment by brandonferens** [comment]
@skoyah I have merged this request. Sorry it took so long.

**Comment by skoyah** [comment]
Thanks mate! No worries!

**Comment by skoyah** [comment]
@brandonferens could you tag the new release?

**Comment by brandonferens** [comment]
@skoyah It has been tagged as `1.0.7`

**Pull request merged**
